name: Adriana Cansian
favicon: null
layout_spectrum: 0.2551382011733949
typography_spectrum: 0.015933807939291
title: Adriana de Moraes Cansian | Direito Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2912660175934434
  lightness: 0.4179596835747361
  saturation: 0.781571846222505
  rhythmicContrast: 0.8299160827882588
purpose: []
