name: Adriana Cansian
favicon: null
layout_spectrum: 0.49376
typography_spectrum: 0.25451
title: Adriana de Moraes Cansian | Direito Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010c08'
    - '#5f5f5f'
    - '#ece1dc'
    - '#b8bcc9'
    - '#828083'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
